source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from accounts.views import *

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create/', register_view, name='create'),
    path('register/activate/', user_activate, name='user_activate'),
    path('profile/<pk>/', UserDetailView.as_view(), name='user_detail'),
    path('profile/<pk>/edit', UserChangeView.as_view(), name='user_update'),
    path('profile/<pk>/change_password/', UserPasswordChangeView.as_view(), name='user_change_password'),
    path('profiles/', ProfilesListView.as_view(), name='profiles_list'),

]

app_name = 'accounts'

source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.__init__ import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/add-review/', ReviewForProductCreateView.as_view(), name='product_review_create'),
    path('review/<int:pk>/edit/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

app_name = 'webapp'

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from uuid import uuid4


class Token(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE,
                             verbose_name='user', related_name='registration_tokens')
    token = models.UUIDField(verbose_name='Token', default=uuid4)

    def __str__(self):
        return str(self.token)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    about = models.TextField(null=True, blank=True, verbose_name='О себе')
    github_profile = models.URLField(null=True, blank=True, verbose_name='Профиль на  Github')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/webapp/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = (
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', 'Продукты питания'),
    ('household', 'Хоз. товары'),
    ('toys', 'Детские игрушки'),
    ('appliances', 'Бытовая Техника')
)


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория')
    description = models.CharField(null=True, blank=True, max_length=300, verbose_name='Описание')
    picture = models.ImageField(upload_to='product_images', null=True, blank=True, verbose_name='Картинка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name='Пользователь', related_name='reviews')
    product = models.ForeignKey('Product', null=True, blank=True, related_name='reviews', on_delete=models.CASCADE,
                                verbose_name='Товар')
    review = models.CharField(max_length=300, verbose_name='Отзыв')
    point = models.IntegerField(verbose_name='Оценка', validators=[MinValueValidator(0), MaxValueValidator(5)])

    def __str__(self):
        return "{} / {} - {}".format(self.product, self.user, self.point)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError


from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from accounts.models import Profile


class UserCreationForm(forms.Form):
    username = forms.CharField(max_length=100, label='Username', required=True)
    password = forms.CharField(max_length=100, label='Password', required=True,
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, label='Password Confirm', required=True,
                                       widget=forms.PasswordInput)
    email = forms.EmailField(label='Email', required=True)

    first_name = forms.CharField(max_length=100, label='first_name', required=False,)
    last_name = forms.CharField(max_length=100, label='last_name', required=False,)

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('User with this email already exists',
                                  code='user_email_exists')
        except User.DoesNotExist:
            return email

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('User with this username already exists',
                                  code='user_username_exists')
        except User.DoesNotExist:
            return username

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        if password_1 != password_2:
            raise ValidationError('Passwords do not match',
                                  code='passwords_do_not_match')
        elif first_name == '' and last_name == '':
            raise ValidationError('You should to write first or last name',
                            code='user_name')
        # elif first_name != '':
        #     return first_name
        # elif last_name != '':
        #     return last_name

        return self.cleaned_data


class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    about = forms.CharField(label='О себе', required=False)
    github_profile = forms.URLField(label='Профиль GitHub', required=False)

    def get_initial_for_field(self, field, field_name):
        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)
        return super().get_initial_for_field(field, field_name)

    def save(self, commit=True):
        user = super().save(commit=commit)
        self.save_profile(commit)
        return user

    def save_profile(self, commit=True):
        profile, _ = Profile.objects.get_or_create(user=self.instance)
        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data.get(field))
        if commit:
            profile.save()

    def clean_github_profile(self):
        github_profile = self.cleaned_data.get('github_profile')
        if 'https://github.com/' not in github_profile:
            raise ValidationError('Invalid url.', code='invalid_url')
        return github_profile


    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'about', 'github_profile']
        profile_fields = ['avatar', 'about', 'github_profile']


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password', widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm', widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Old Password', widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data['password']
        password_2 = self.cleaned_data['password_confirm']
        if password_1 != password_2:
            raise ValidationError('Passwords do not match', code='passwords_do_not_match')
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView

from accounts.models import Token, Profile
from main.settings import HOST_NAME
from .forms import UserCreationForm, UserChangeForm, UserChangePasswordForm


def register_view(request):
    if request.method == 'GET':
        form = UserCreationForm()
        return render(request, 'user_create.html', {'form': form})
    elif request.method == 'POST':
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                is_active=False
            )
            user.set_password(form.cleaned_data['password'])
            user.save()
            Profile.objects.create(user=user)

            token = Token.objects.create(user=user)
            activation_url = HOST_NAME + reverse('accounts:user_activate') + '?token={}'.format(token)

            user.email_user('Регистрация на сайте localhost',
                            'Для активации перейдите по ссылке: {}'.format(activation_url))

            return redirect("webapp:index")
        else:
            return render(request, 'user_create.html', {'form': form})


def user_activate(request):
    token_value = request.GET.get('token')
    try:
        token = Token.objects.get(token=token_value)

        user = token.user
        user.is_active = True
        user.save()

        token.delete()

        login(request, user)

        return redirect('webapp:index')
    except Token.DoesNotExist:
        return redirect('webapp:index')


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:user_detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UpdateView):
    model = User
    template_name = 'user_password_change.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def text_func(self):
        return self.get_object() == self.request.user

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:login')


class ProfilesListView(ListView):
    template_name = 'profiles.html'
    context_object_name = 'profiles'
    model = User
    paginate_by = 10
    paginate_orphans = 1

source/accounts/templates/profiles.html
{% extends 'base.html' %}

{% block menu %}
    {% if request.user.is_authenticated %}
        <li><a href="{% url 'webapp:project_create' %}">Add Project</a></li>
    {% endif %}
    <li><a href="{% url 'webapp:project_create' %}">Add Project</a></li>
{% endblock %}

{% block content %}
    {% include 'partial/form_field.html' %}
    <h1>Projects:</h1>
    <hr/>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
        {% for profile in profiles %}
            <a href="{% url 'accounts:user_detail' profile.pk %}">{{ profile.username }}</a>
            <hr/>
        {% endfor %}

    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}

{% block content %}
    <h1 class="text-center">Регистрация</h1>
    <form action="{% url 'accounts:create' %}" method="post" class="text-center">
        {% csrf_token %}
        {% for error in form.non_field_errors %}
            <p class="form-error">{{ error }}</p>
        {% endfor %}
        {% for field in form %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}" class="form-label
            {% if field.field.required %}required{% endif %}">{{ field.label }}</label>
                {% if field.errors %}
                    {{ field }}
                    {% for error in field.errors %}
                        <p class="form-error">{{ error }}</p>
                    {% endfor %}
                {% else %}
                    {{ field }}
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Edit profile</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Профиль: {{ user_obj.username }}</h1>
    {% if not user_obj.profile.avatar or user_obj.profile.avatar == 'False' %}
        {% load static %}
        <img class="avatar" src="{% static 'img/nofoto.png' %}" width="250" height="250" alt="no picture">
    {% else %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <p>Имя: <b>{{ user_obj.first_name }}</b></p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>О себе: {{ user_obj.profile.about }}</p>
    <p>Почта: {{ user_obj.email }}</p>
    <p>GitHub: <a href="{{ user_obj.profile.github_profile }}">{{ user_obj.profile.github_profile }}</a></p>

    <h3>Отзывы:</h3>
    {% for review in user_obj.reviews.all %}
        <div class="task">
            <p><b><a href="{% url 'accounts:user_detail' review.user_id %}">{{ review.user }}</a></b></p>
            <p>Email: {{ review.user.email }}</p>
            <p>Отзыв: {{ review.review }}</p>
            <p>Оценка: </p>
            {% if review.point == 1 %}
                {% load static %}
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
            {% elif review.point == 2 %}
                {% load static %}
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
            {% elif review.point == 3 %}
                {% load static %}
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
            {% elif review.point == 4 %}
                {% load static %}
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
            {% elif review.point == 5 %}
                {% load static %}
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
                <img class="star" src="{% static 'img/star.jpg' %}" width="30" height="30" alt="star">
            {% endif %}

            <p class="projects-links">
                {% if perms.webapp.change_product or request.user == review.user %}
                    <a href="{% url 'webapp:review_update' review.pk %}">Edit</a>
                {% endif %}
                {% if perms.webapp.delete_product or request.user == review.user %}
                    <a href="{% url 'webapp:review_delete' review.pk %}">Delete</a>
                {% endif %}
            <br>
            </p>
        </div>
    {% empty %}
        <p>Нет отзывов.</p>
    {% endfor %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_update' user_obj.pk %}">Update Profile password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Change Password: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
        {% include 'partial/form.html' with button_text="Save" %}
    </form>
{% endblock %} %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li><a href="{% url 'accounts:user_detail' user_obj.pk %}">View</a></li>
        <li><a href="{% url 'accounts:user_change_password' user_obj.pk %}">Change password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <h1>Edit profile: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
{% endblock %}