source/main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views.__init__ import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('product/<int:pk>/', ProductView.as_view(), name='product_view'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/<int:pk>/edit/', ProductUpdateView.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    path('product/<int:pk>/add-review/', ReviewForProductCreateView.as_view(), name='product_review_create'),
    path('review/<int:pk>/edit/', ReviewUpdateView.as_view(), name='review_update'),
    path('review/<int:pk>/delete/', ReviewDeleteView.as_view(), name='review_delete'),
]

app_name = 'webapp'

source/webapp/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


DEFAULT_CATEGORY = 'other'
CATEGORY_CHOICES = (
    (DEFAULT_CATEGORY, 'Разное'),
    ('food', 'Продукты питания'),
    ('household', 'Хоз. товары'),
    ('toys', 'Детские игрушки'),
    ('appliances', 'Бытовая Техника')
)


class Product(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default=CATEGORY_CHOICES[0][0],
                                verbose_name='Категория')
    description = models.CharField(null=True, blank=True, max_length=300, verbose_name='Описание')
    picture = models.ImageField(upload_to='product_images', null=True, blank=True, verbose_name='Картинка')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL,
                             verbose_name='Пользователь', related_name='reviews')
    product = models.ForeignKey('Product', null=True, blank=True, related_name='reviews', on_delete=models.CASCADE,
                                verbose_name='Товар')
    review = models.CharField(max_length=300, verbose_name='Отзыв')
    point = models.IntegerField(verbose_name='Оценка', validators=[MinValueValidator(0), MaxValueValidator(5)])

    def __str__(self):
        return "{} / {} - {}".format(self.product, self.user, self.point)

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

source/webapp/forms.py
from django import forms
from webapp.models import Product, Review


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'category', 'description', 'picture']


class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review', 'point']

source/webapp/views/product_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.forms import ProductForm
from webapp.models import Product


class IndexView(ListView):
    template_name = 'product/index.html'
    context_object_name = 'products'
    model = Product
    ordering = 'name'


class ProductView(DetailView):
    template_name = 'product/product.html'
    pk_url_kwarg = 'pk'
    model = Product


class ProductCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'product/create.html'
    model = Product
    form_class = ProductForm
    permission_required = 'webapp.add_product'
    permission_denied_message = "Доступ запрещён"

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    model = Product
    template_name = 'product/update.html'
    form_class = ProductForm
    context_object_name = 'obj'
    permission_required = 'webapp.change_product'
    permission_denied_message = "Доступ запрещён"

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'product/delete.html'
    model = Product
    context_object_name = 'obj'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_product'
    permission_denied_message = "Доступ запрещён"

source/webapp/templates/product/index.html
{% extends 'base.html' %}

{% block menu %}
    {% if perms.webapp.add_product %}
        <li><a href="{% url 'webapp:product_create' %}">Add Product</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Products:</h1>
    <hr/>
{#    {% if is_paginated %}#}
{#        {% include 'partial/pagination.html' %}#}
{#    {% endif %}#}
{#    <form method="POST" action="{% url "webapp:mass_delete"  %}">#}
{#        {% csrf_token %}#}

        {% for product in products %}
            <h2>{{ product.name }}</h2>
            <div>Категория: {{ product.category }}</div>
            <a href="{% url 'webapp:product_view' product.pk %}">More...</a>
            {% if perms.webapp.change_product %}
                <a href="{% url 'webapp:product_update' product.pk %}">Edit</a>
            {% endif %}
            {% if perms.webapp.delete_product %}
                <a href="{% url 'webapp:product_delete' product.pk %}">Delete</a>
            {% endif %}
            <hr/>
        {% endfor %}

{#        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">#}
{#          Delete#}
{#        </button>#}
{##}
{#        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#          <div class="modal-dialog" role="document">#}
{#            <div class="modal-content">#}
{#              <div class="modal-header">#}
{#                <h5 class="modal-title" id="exampleModalLabel">Are you sure want to delete task?</h5>#}
{#                <button type="button" class="close" data-dismiss="modal" aria-label="Close">#}
{#                  <span aria-hidden="true">&times;</span>#}
{#                </button>#}
{#              </div>#}
{#              <div class="modal-footer" style="justify-content: center">#}
{#                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
{#                <input type="submit" value="Delete" class="btn btn-primary">#}
{#              </div>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{##}
{#    </form>#}
{#    {% if is_paginated %}#}
{#        {% include 'partial/pagination.html' %}#}
{#    {% endif %}#}
{% endblock %}